development:
  adapter: mysql2
  database: 12doo-dev
  pool: 5
  encoding: utf8
  username: root

test:
    adapter: mysql2
    database: 12doo-test
    pool: 5
    encoding: utf8
    username: root

production:
    adapter: mysql2
    database: 12doo
    pool: 5
    encoding: utf8
    username: root